### ISSUE TITLE
darknet convert to caffe model and detection

### ISSUE THREAD

**Issue by youngxiao** [ysh329/darknet2caffe#9]
@ysh329 Hey, Thanks for your repository. I successfully convert my darknet model to caffe model with a region layer. However it cannot be used to detect images. Do you have some ideas?

Thanks in advance.

**Comment by ysh329** [comment]
You can search some non-official caffe repo. which have region layers, such as caffe-yolo etc. Or you can implement one according to darknet's simple codes.

**Comment by youngxiao** [comment]
@ysh329 Thanks, It is critical to find appropriate Caffe that could load such a model. I'll try the repo. you mentioned, god bless me.
